L02P02_2021JS650_2021SZ650/Models/ComentariosLibro.cs
using System;
using System.Collections.Generic;

namespace L02P02_2021JS650_2021SZ650.Models;

public partial class ComentariosLibro
{
    public int Id { get; set; }

    public int? IdLibro { get; set; }

    public string? Comentarios { get; set; }

    public string? Usuario { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Libro? IdLibroNavigation { get; set; }
}

L02P02_2021JS650_2021SZ650/Controllers/ComentariosLibroController.cs
using L02P02_2021JS650_2021SZ650.Models;
using Microsoft.AspNetCore.Mvc;

namespace L02P02_2021JS650_2021SZ650.Controllers
{
    public class ComentariosLibroController : Controller
    {
        private readonly LibreriaDbContext _libreriaDbContext;

        public ComentariosLibroController(LibreriaDbContext libreriaDbContext)
        {
            _libreriaDbContext = libreriaDbContext;
        }

        public IActionResult Index(int id)
        {
            var info = (from a in _libreriaDbContext.Autores
                            join l in _libreriaDbContext.Libros on a.Id equals l.IdAutor
                            where l.Id == id
                            select new {
                                autor = a.Autor,
                                libro = l.Nombre,
                                id_libro = l.Id
                            }).FirstOrDefault();

            var comentarios = (from c in _libreriaDbContext.ComentariosLibros
                               join l in _libreriaDbContext.Libros on c.IdLibro equals l.Id
                               where l.Id == id
                               select new
                               {
                                   comentario = c.Comentarios,
                                   usuario = c.Usuario,
                                   fecha = c.CreatedAt
                               }).ToList();

            ViewData["autor"] = info.autor.ToString();
            ViewData["libro"] = info.libro.ToString();
            ViewData["id_libro"] = info.id_libro.ToString();
            ViewData["comentarios"] = comentarios;
            return View();
        }

        public IActionResult AddComment(AddCommentModel model)
        {
            string comment = model.comment;
            string idLibro = model.id_libro;
            string autor = model.autor;

            var comentarios = (from c in _libreriaDbContext.ComentariosLibros
                               join l in _libreriaDbContext.Libros on c.IdLibro equals l.Id
                               where l.Id == int.Parse(idLibro)
                               select new
                               {
                                   id = c.Id,
                                   comentario = c.Comentarios,
                                   usuario = c.Usuario,
                                   fecha = c.CreatedAt
                               }).ToList();

            ComentariosLibro cl = new ComentariosLibro();
            cl.Id = (_libreriaDbContext.ComentariosLibros.OrderBy(cl => cl.Id).LastOrDefault()?.Id ?? 0) + 1;
            cl.Comentarios = comment;
            cl.IdLibro = int.Parse(idLibro);
            cl.Usuario = autor;
            cl.CreatedAt = DateTime.Now;
            _libreriaDbContext.ComentariosLibros.Add(cl);
            _libreriaDbContext.SaveChanges();

            comentarios.Add(new
            {
                id = cl.Id,
                comentario = cl.Comentarios,
                usuario = cl.Usuario,
                fecha = cl.CreatedAt
            });

            var info = (from a in _libreriaDbContext.Autores
                        join l in _libreriaDbContext.Libros on a.Id equals l.IdAutor
                        where l.Id == int.Parse(idLibro)
                        select new
                        {
                            autor = a.Autor,
                            libro = l.Nombre,
                            id_libro = l.Id
                        }).FirstOrDefault();

            ViewData["autor"] = info.autor.ToString();
            ViewData["libro"] = info.libro.ToString();
            ViewData["id_libro"] = idLibro;
            ViewData["comentarios"] = comentarios;
            ViewData["disableForm"] = true; 
            return View("Index");
        }
    }

    public class AddCommentModel ()
    {
        public string comment { get; set; }
        public string id_libro { get; set; }
        public string autor { get; set; }
    }
}

L02P02_2021JS650_2021SZ650/Views/ComentariosLibro/Index.cshtml
<div style="padding-top:30px">
    <ul class="progressbar">
        <li>Autores</li>
        <li>Libros</li>
        <li class="@(ViewData["disableForm"] == null ? "active" : "")">Comentarios Existentes</li>
        <li class="@(ViewData["disableForm"] != null ? "active" : "")">Nuevo Comentario</li>
    </ul>
</div>

<div style="padding-top:80px">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-3">
                    <h5>Autor</h5>
                </div>
                <div class="col-md-3">
                    @*lo de estas madres no sé muy bien cómo funciona, pero lo puse por si acaso*@
                    @Html.Label("lblAutorSelec", (string)ViewData["autor"])
                </div>
                <div class="col-md-3">
                    <h5>Libro</h5>
                </div>
                <div class="col-md-3">
                    @Html.Label("lblLibroSelec", (string)ViewData["libro"])
                </div>
            </div>
        </div>
    </div>

    <div class="row py-5">
        <div class="col-md-6">
            <h5>Comentarios Existentes</h5>
            <div class="">
                <div class="card" style="width: contain;">
                    <ul class="list-group list-group-flush">
                        @foreach (var comentario in (IEnumerable<dynamic>)ViewData["comentarios"])
                        {
                            <li class="list-group-item">
                                <p>@comentario.comentario</p>
                                <small>@comentario.usuario</small>
                                <br />
                                <small>@comentario.fecha</small>
                            </li>
                        }                       
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            @using(Html.BeginForm("AddComment", "ComentariosLibro", FormMethod.Post))
            {
                
            }
            <form asp-action="AddComment">
                <h5>Agregar un Comentario</h5>
                <small>Comentario</small>
                @if (ViewData["disableForm"] == null)
                {
                    @Html.TextArea("comment", "", new { @class = "form-control", id = "idComentarios", style = "min-height: 150px;" })
                } else
                {
                    @Html.TextArea("comment", "", new { @class = "form-control", id = "idComentarios", style = "min-height: 150px;", disabled = true })
                }
                @Html.Hidden("id_libro", (string)ViewData["id_libro"])
                @Html.Hidden("autor", (string)ViewData["autor"])
                <div class="py-2">
                    <div class="card">
                        <div class="card-body p-1">
                            @if (ViewData["disableForm"] == null)
                            {
                                <button type="submit" class="btn btn-success w-100">Guardar comentario</button>
                            } else
                            {
                                <button type="submit" class="btn btn-success w-100" disabled>Comentario: Adicionado con éxito</button>
                            }
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>